EventBook/Controllers/AccountManagementController.cs
using ID7Digital.EventBook.Domain.Enum;
using ID7Digital.EventBook.Domain.Helpers;
using ID7Digital.EventBook.Domain.Models;
using ID7Digital.EventBook.Services.Abstract;
using ID7Digital.EventBook.Services.Concrete;
using ID7Digital.EventBook.Services.ViewModels;
using ID7Digital.EventBook.UI.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ID7Digital.EventBook.UI.Controllers
{
    public class AccountManagementController : AccountBaseController
    {
        public ActionResult Index(IAccountService accountService)
        {
            var account = GetCurrentAccount(accountService);
            return View("ProfileManagement/Details", account);
        }


        public ActionResult SignIn(string returnUrl, bool mobile = false)
        {
            var vm = new SignInModel
            {
                ReturnUrl = returnUrl,
                ShowClientCertificateLink = false,
                IsSigninRequest = mobile
            };

            return View();
        }

        [HttpPost]
        public ActionResult SignIn(SignInModel model, IAccountService accountRepo, IUserService userManagementService, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var userAccount = accountRepo.FindAccountByUserName(model.UserName);
                var validLogin = userAccount != null && Membership.ValidateUser(model.UserName.ToLower(), model.Password); ;

                if (userAccount != null)
                {
                    // Check if the account is locked. If so, try to unlock it (if 24 hours have passed).
                    if (userAccount.IsLocked && accountRepo.TryUnlockAfterWaitingPeriod(userAccount.UserName, 86400))
                    {
                        ModelState.AddModelError("", "Account Locked. It will be unlocked automatically after 24 hours or through password reset");

                        return View(model);
                    }

                    // If, after the previous validation, the account is finally unlocked, proceed.
                    if (!userAccount.IsLocked)
                    {
                        if (validLogin)
                        {
                            if (userAccount.IsActivated)
                            {
                                accountRepo.UpdateLoginAttemptTracking(userAccount.UserName, true);

                                return SignInPortal(
                                    userAccount.UserName,
                                    model.Password,
                                    model.ReturnUrl,
                                    model.EnableSSO,
                                    userAccount);
                            }

                            return GetActivationLinkResendView(userAccount.UserName, accountRepo, null);

                        }

                        ModelState.AddModelError("", "Your username or password was entered incorrectly.");

                        var maxAttempts = int.Parse(ConfigurationManager.AppSettings["maxInvalidLogginAttempts"]);

                        var remainingAttempts = maxAttempts - userAccount.FailedAttemptsCount;

                        if (remainingAttempts <= 1)
                        {
                            var message = remainingAttempts == 1
                                              ? "Account will be locked with next failed login attempt"
                                              : "Account is locked and it will unlock automatically after 24 hours";
                            ModelState.AddModelError("", message);
                        }

                        accountRepo.UpdateLoginAttemptTracking(userAccount.UserName, false);

                    } // End user not locked
                }
                else
                {
                    ModelState.AddModelError("", "Your username or password was entered incorrectly.");
                } // End user account not null f
            } // End valid ModelState
            else
            {
                ModelState.AddModelError("", "Your username or password was entered incorrectly.");

            }

            return View(model);
        }

        [HttpPost]
        public JsonResult SaveProfile(string section, Account account, IAccountService accountService)
        {
            var success = false;
            var partialContent = string.Empty;

           var accountEntity = accountService.GetAccountById(account.ID);


            switch (section.ToLower())
            {
                case "contactinformation" :
                accountEntity.FirstName = account.FirstName;
                accountEntity.LastName = account.LastName;
                accountEntity.JobTitle = account.JobTitle;
                accountEntity.DisplayName = account.DisplayName;
                break;
                case  "Details": 
                break;
                case  "AdditionalContactInformation":
                  break;
                case "ProfileAddress":
                break;
                case "ProfilePicture":
                break;
             

            }
            accountService.SaveChanges();

            if (accountEntity != null)
            {                     
                    // Change the last update date
                    account.LastUpdated = DateTime.Now;

                    // Add in the titles view data
                    if (section.ToLower() == "contactinformation")
                    {
                        // add in titles view data ...
                        GetSelectListFromEnumTitleType(account);
                    }

                    // Render partial view to be sent back to replace part of the profile edit
                    partialContent = PartialViewToString(@"ProfileManagement\" + section, account);
                success = true;
            }

            return Json(new
            {
                Success = success,
                Html = partialContent,
            }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult ProfileManagement(IAccountService accountService)
        {
            var account = GetCurrentAccount(accountService);

            var partialViewToString = PartialViewToString(@"ProfileManagement\Details", account);

            return Json(new { Html = partialViewToString }, JsonRequestBehavior.AllowGet);
        }

  

        [HttpGet]
        public JsonResult ProfileContactInformation(IAccountService accountService)
        {
            var account = GetCurrentAccount(accountService);

            GetSelectListFromEnumTitleType(account);

            var partialViewToString = PartialViewToString(@"ProfileManagement\ContactInformation", account);

            return Json(new { Html = partialViewToString }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult AdditionalContactInformation(IAccountService accountService)
        {
            var account = GetCurrentAccount(accountService);

            GetSelectListFromEnumTitleType(account);

            var partialViewToString = PartialViewToString(@"ProfileManagement\AdditionalContactInformation", account);

            return Json(new { Html = partialViewToString }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ProfileAddress(IAccountService accountService)
        {
            var account = GetCurrentAccount(accountService);

            var partialViewToString = PartialViewToString(@"ProfileManagement\ProfileAddress", account);

            return Json(new { Html = partialViewToString }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ProfilePicture(IAccountService accountService)
        {
            var account = GetCurrentAccount(accountService);

            var partialViewToString = PartialViewToString(@"ProfileManagement\ProfilePicture", account);

            return Json(new { Html = partialViewToString }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ResetPasswordRequest()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ResetPasswordRequest(ActivationEmailModel emailModel, IAccountService accountRepo, IUserService userManagementService)
        {
            if (ModelState.IsValid)
            {
                string resetCode;
                var userAccount = accountRepo.FindAccountByUserName(emailModel.UserName);

                var resetSuccess = accountRepo.StartEmailResetPasswordProcess(emailModel.UserName, emailModel.Email, out resetCode);

                if (resetSuccess)
                {
                    emailModel.FirstName = userAccount.FirstName;

                    var resetEmailSuccess = ResetPasswordRequestSendEmail(emailModel, resetCode);

                    if (resetEmailSuccess)
                    {
                        return View("EventBookPasswordResetEmailSent");
                    }
                }

                ModelState.AddModelError("ResetPasswordRequest",  "The specified user name or email address is invalid.");
            }

            return View();
        }

        private ActionResult GetActivationLinkResendView(string userName, IAccountService accountRepo, IUserService userManagementRepository)
        {
            var userAccount = accountRepo.FindAccountByUserName(userName);
            var timeDifferenceFromSignUpIn = DateTime.Now.Subtract(userAccount.DateRegistered);

            if (timeDifferenceFromSignUpIn.TotalMinutes >= Double.Parse(ConfigurationManager.AppSettings["MinutesTillDeactiveAccount"]))
            {
                // Delete Account Record 
                accountRepo.RemoveAccount(userAccount);
                accountRepo.SaveChanges();

EventBook/Views/Event/ActivationEmail.cshtml
@model ID7Digital.EventBook.Services.ViewModels.ActivationEmailModel



@{
    ViewBag.Title = "ActivationEmail";
}

<h2>ActivationEmail</h2>

 <p>Dear @Model.FirstName,</p>
    <p>You recently registered for an IRIS account.</p>
    <p>Your username is: @Model.UserName</p> 
    <p>To complete setup of your account please click the following link: @Model.ActivationLink</p>

EventBook/Views/Event/Demo.cshtml
@{
    Layout = null;
}

<h2>Users</h2>
<div>


    <div class="grid-style" data-ng-grid="userGrid">
    </div>

    <div class="user-details" data-ng-show="selectedUser">

        <div>
            <ul>
                <li data-ng-repeat="user in selectedUsers">{{user.FirstName}}</li>
            </ul>
        </div>

        <div class="well well-large">
            <h3>User Details</h3>
            <form>
                <label for="firstName">First Name</label>
                <input type="text" id="firstName" name="firstName" data-ng-model="selectedUser.FirstName" />
                <label for="lastName">Last Name</label>
                <input type="text" id="lastName" name="lastName" data-ng-model="selectedUser.LastName" />
                <label for="gender">Gender</label>
                <input type="radio" id="male" name="gender" data-ng-checked="!selectedUser.Gender" /><span class="gender-text">Male</span>
                <input type="radio" id="female" name="gender" data-ng-checked="selectedUser.Gender" /><span class="gender-text">Female</span><br />
                <br />
                <label for="mobile">Mobile</label>
                <input type="tel" id="mobile" name="mobile" data-ng-model="selectedUser.Mobile" />
                <label for="email">Email</label>
                <input type="email" id="email" name="email" data-ng-model="selectedUser.email" />
                <label for="country">Country</label>
                <select id="country" name="country" data-ng-model="selectedUser.country" data-ng-options="c.id as c.name for c in countryList"></select>
                <label for="state">State</label>
                <select id="state" name="state" data-ng-model="selectedUser.state" data-ng-change="clearCityAndZip();" data-ng-options="s.id as s.name for s in countryList[0].states"></select>
                <label for="city">City</label>
                <select id="city" name="city" data-ng-model="selectedUser.city" data-ng-options="c.id as c.name for c in selectedState.cities">
                    <option value="" selected="selected">Select City</option>
                </select>
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" data-ng-model="selectedUser.zip" /><br />
                <input type="button" id="btnSubmit" class="btn" data-ng-click="updateUser(selectedUser)" value="UPDATE" />
            </form>
        </div>

    </div>
</div>

EventBook/Views/Event/EventBookActivated.cshtml
@model ID7Digital.EventBook.Services.ViewModels.ActivationViewModel

@{
    ViewBag.Title = "EventBookActivated";
}

    @if (Model.ActivationCompleted)
    {
        @Html.Partial("../AccountManagement/SignIn", Model.SignIn)
    }
    else
    {
         <h2>There was an error while processing your request. Your EventBook account has not been activated</h2>
    }

EventBook/Views/Event/Index.cshtml
@*@model ID7Digital.EventBook.Services.ViewModels.SignInModel

@{
    ViewBag.Title = "Index";
}

@Html.Partial("../AccountManagement/SignIn", Model)*@
@using System.Web
@using Microsoft.AspNet.Identity
@using Microsoft.Owin.Security


@if (Request.IsAuthenticated)
{
    <h3>Welcome @User.Identity.GetUserName() </h3>

    // Angular directives
    // Main name of the ng module, and controller to manage the services, ng view for where view directed in spa.
    <div data-ng-app="main" data-ng-controller="RootController">
        <ul>
            <li data-ng-class="{active : activeViewPath==='/demo'}"><a href="#/demo">Demo</a></li>
            <li data-ng-class="{active : activeViewPath==='/account'}"><a href="#/account">Account Settings</a></li>
        </ul>
        <div data-ng-view=""></div>
    </div>

}
else
{
    <h4>You are not logged in, Please use a service to log in.</h4>
    <hr />

    //get list of configured external authentication middleware
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0)
    {
        <div>
            <p>There are no external authentication services configured</p>
        </div>
    }
    else
    {
        using (Html.BeginForm("ExternalLogin", "Event"))
        {
            @Html.AntiForgeryToken()
            <div id="socialLoginList">
                <p>
                    @foreach (AuthenticationDescription p in loginProviders)
                    {
                        <button type="submit" class="btn btn-default" id="@p.AuthenticationType"
                                name="provider" value="@p.AuthenticationType"
                                title="Log in using your @p.Caption account">
                            @p.AuthenticationType
                            </button>
                    }
                </p>
            </div>
        }
    }
}

EventBook/Views/Event/InitialRegistration.cshtml
@{
    ViewBag.Title = "InitialRegistration";
}

 <h1>EventBook Account</h1>
        <h2>Thank you for registering.</h2>
        <p>An email confirmation has been sent to you. Please click the authentication link in the email to finish setting up your account.</p>

EventBook/Views/Event/InvalidPasswordResetLink.cshtml
@{
    ViewBag.Title = "InvalidPasswordResetLink";
}

<h2>InvalidPasswordResetLink</h2>

EventBook/Views/Event/SetPassword.cshtml
@model ID7Digital.EventBook.Services.ViewModels.ResetPasswordModel
@{
    ViewBag.Title = "Set Password";
}


@using (Html.BeginForm("SetPassword", "Event", FormMethod.Post))
{
    <fieldset>
        <legend>Set Password</legend>
          @Html.HiddenFor(x => x.UserName)

        <div class="editor-label">
            @Html.LabelFor(x => x.NewPassword)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.NewPassword)
        </div>
        <div class="editor-label">
            @Html.LabelFor(x => x.ConfirmPassword)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.ConfirmPassword)
        </div>
        <div class="editor-label">
            @Html.LabelFor(x => x.SecretQuestion)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.SecretQuestion)
        </div>
        <div class="editor-label">
            @Html.LabelFor(x => x.SecretQuestionAnswer)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.SecretQuestionAnswer)
        </div>
        <p>
            <input type="submit" value="Change Password" />
        </p>
    </fieldset>
}

EventBook/Views/Event/SignUp.cshtml
@model ID7Digital.EventBook.Services.ViewModels.SignUpModel

@{
   Layout = "../Shared/_Layout.SignUp.cshtml"; 
}


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SignUpModel</legend>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName, new { data_val = "true", data_val_remote = "User Name Already Exists!", data_val_remote_url = "/AccountManagement/IsValidNewUserName" })
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email, new { data_val = "true", data_val_remote = "Email Address Already Exists!", data_val_remote_url = "/AccountManagement/IsValidNewEmailAddress" })
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password, new {@class = "PasswordStrengthCheck"})
            @Html.ValidationMessageFor(model => model.Password)
        </div>
        <div class="PasswordStrengthListItem">
			                @Html.Partial("PasswordStrengthCheck")
	   </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ConfirmPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ConfirmPassword)
            @Html.ValidationMessageFor(model => model.ConfirmPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TermsAndConditions)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TermsAndConditions)
            @Html.ValidationMessageFor(model => model.TermsAndConditions)
        </div>

        <p>
            <input type="submit" value="Register" />
        </p>
    </fieldset>
}

<b>
    @Html.ActionLink("Already A Member Sign In Here", "SignIn", "AccountManagement")
</b>


@section scripts
{
    <script type="text/javascript">
        $(function () {
            Common.PasswordManagement();
        });
    </script>
}

EventBook/Views/Event/WelcomeEmail.cshtml
@model ID7Digital.EventBook.Services.ViewModels.ActivationEmailModel

@{
    ViewBag.Title = "WelcomeEmail";
}

<h2>WelcomeEmail</h2>

<p>Dear @Model.FirstName,</p>

<p>Congratulations!</p>

<p>Your Username is: @Model.UserName</p>
<p>Please Login at: @Model.LoginURL</p>

<p>If you forget your username or password you can get help by clicking the "problems logging in" link on the login page.</p>